signal_generator:
  ros__parameters:
    default: 
      type_: "sine"
      amplitude_: 0.5
      frequency_: 2.0
      offset_: 0.0
      phase_: 2.0
      time_: 0.0
    square:
      type_: "square"
      amplitude_: 2.0
      frequency_: 5.0
      offset_: -1.0
      phase_: 0.0
      time_: 0.0
    sawtooth:
      type_: "sawtooth"
      amplitude_: 1.0
      frequency_: 10.0
      offset_: 2.5
      phase_: 0.7853
      time_: 0.0

reconstructor_node:
      default: 
        type_: "sine"
        amplitude_: 0.5
        frequency_: 2.0
        offset_: 0.0
        phase_: 2.0
        time_: 0.0
    square:
      type_: "square"
      amplitude_: 2.0
      frequency_: 5.0
      offset_: -1.0
      phase_: 0.0
      time_: 0.0
    sawtooth:
      type_: "sawtooth"
      amplitude_: 1.0
      frequency_: 10.0
      offset_: 2.5
      phase_: 0.7853
      time_: 0.0